site_name: Reloaded-3 Localisation API
site_url: https://github.com/TheBestAstroNOT/reloaded3.localisation

repo_name: reloaded3.localisation
repo_url: https://github.com/TheBestAstroNOT/reloaded3.localisation

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Reloaded-Project
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/sewer56.dev

extra_css:
  - Reloaded/Stylesheets/extra.css

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    scheme: reloaded3-slate
  features:
    - navigation.instant

plugins:
  - search
  - exclude-unused-files:
      file_types_to_check: [ "psd", "7z", "kra" ]
      file_types_override_mode: append
      enabled: true
  - exclude:
      # Exclude the Theme's own files.
      glob:
        - Reloaded/Pages/*
        - Reloaded/docs/*
        - Reloaded/Readme.md
        - Reloaded/LICENSE
        - Reloaded/mkdocs.yml

nav:
  - Home: index.md
  - Creating a LocaleTable: functions/get_locale_table.md
  - Freeing a LocaleTable: functions/free_locale_table.md
  - Fetching a value from a LocaleTable: functions/get_entry.md
  - Manually handling parsing: functions/parse_r3locale_bytes.md